### ISSUE TITLE
Threshold dependencies

### ISSUE THREAD

**Issue by mjc239** [mjc239/mjc239.github.io#13]
Show thresholds only depend on current, not previous days

**Comment by blujay92** [comment]
As it stands there is a very brief explanation of this buried in the section entitled "An instructive example revisited: Uniformly distributed quotes".

I'm not certain what is the best solution, but I don't think the current situation is a satisfactory one.

**Comment by blujay92** [comment]
My mistake, this is alluded to earlier in Post 2, but I added a section "Carpe rāpa!: optimality and sticking to your guns" which covers this.

Could you give this a look and close if you're happy?

**Comment by blujay92** [comment]
I've now updated the longer form explanation from the second post as well.
