### ISSUE TITLE
Update hyperlinks

### ISSUE THREAD

**Issue by blujay92** [mjc239/mjc239.github.io#16]
When writing I added hyperlinks to the posts before I knew what their hyperlinks would be (e.g. at the end of the first post [post2hyperlink]). These all need sorting out once we decide on the names of the posts.

**Comment by blujay92** [comment]
Speaking of which, these links should obviously only be active once the later posts go up (and moreover the wording will likely need to change).

In this vein I've included a version with no link as "we will give an answer" and a commented version with a dead link and "we give an answer" to be used once the second is up and its title finalised.

**Comment by mjc239** [comment]
The Bartley-Cole constant has a citationneeded hyperlink, did you have an idea of what to link this to?

**Comment by mjc239** [comment]
ATM, I've included the numerically computed calculated value at the end of the section.

**Comment by blujay92** [comment]
Yes sorry I have no idea what I was thinking there with the link. I've removed it.
