### ISSUE TITLE
Graph for thresholds are expectations proof

### ISSUE THREAD

**Issue by blujay92** [mjc239/mjc239.github.io#18]
Would be nice to have a graph for the cases in the more formal proof that the thresholds are the expectations

**Comment by mjc239** [comment]
Not sure I understand this, can you expand?

**Comment by mjc239** [comment]
I think I might understand it - I have put a graph in the Non-negative Turnips section. Can you let me know if this is what you had in mind?

**Comment by blujay92** [comment]
Yes, that's exactly what I had in mind! If I said graphs at any point I was probably thinking of having a graph for each of the two non-optimal cases.

Table looks smashing too!

The only thing I'm wondering, and this is obviously very pedantic, and likely what I wrote first time round, but just because the value is optimal for this function g doesn't mean that the threshold is unique as the pdf could have null regions. It doesn't mean the result is wrong per se, and I'm not saying that anything you've written isn't correct, but I'm not sure whether it needs mentioning or not.

**Comment by mjc239** [comment]
Thanks!

And yeh I get your point - in the extreme case whether the distribution is a sum of Dirac deltas at prices p1 and p2, then clearly the thresholds can be anything between p1 and p2. As you said it doesn't change our results, as our value will always be in the set of optimal values, but we could add a note saying that the threshold is only unique if f(p) is supported in a neighbourhood of the point p=e_{n-i} (do you agree?)

**Comment by mjc239** [comment]
Also I can add an extra graph if you like, something like this:
![image](https://user-images.githubusercontent.com/17711185/104659981-9bf0f680-56bd-11eb-89a3-fb2a55e54e3f.png)

**Comment by blujay92** [comment]
> Thanks!
> 
> And yeh I get your point - in the extreme case whether the distribution is a sum of Dirac deltas at prices p1 and p2, then clearly the thresholds can be anything between p1 and p2. As you said it doesn't change our results, as our value will always be in the set of optimal values, but we could add a note saying that the threshold is only unique if f(p) is supported in a neighbourhood of the point p=e_{n-i} (do you agree?)

Up to you really how you tie it up, but I think that's as good as anything. I suppose you could parenthetically say that this would necessarily include any distribution supported on an interval (even one-sided or two-sided infinite intervals). I only mention this because of the secondary confusion that it being supported in a neighbourhood of e_{n-i} is a bit of a hazy criterion insofar as those values are themselves defined rather indirectly (in particular it's not super obvious what conditions on the pdf would guarantee your condition for all i say). I do agree with you that what you suggested seems morally the right thing to say, just that this could be worth mentioning too.

If you do decide to mention something like this then you could also say that say unif, exp and normal would be included.

**Comment by blujay92** [comment]
> Also I can add an extra graph if you like, something like this:
> ![image](https://user-images.githubusercontent.com/17711185/104659981-9bf0f680-56bd-11eb-89a3-fb2a55e54e3f.png)

Also yes I think two graphs would be great as the whole argument is based on that dichotomy.
