### ISSUE TITLE
Review recap

### ISSUE THREAD

**Issue by mjc239** [mjc239/mjc239.github.io#7]
Review post 2 recap

**Comment by blujay92** [comment]
Just looking at this now. I had originally added the Tim Rogers video kind of as a joke and because I think it's quite funny/unironically agree with it a lot (though I worry that's not the point). Since it's on your site happy for you to make the call whether or not to remove this.

**Comment by blujay92** [comment]
As for the spoilers bit I think that the present formatting of the hidden text is pretty unpleasant, but it would be useful to know how to include collapsible sections in an attractive way. Any ideas?

**Comment by blujay92** [comment]
For now I've put it as a footnote as that looks a bit tidier.

**Comment by mjc239** [comment]
you've got rid of the collapsable sections, and replaced them with footnotes, right? would you rather they be collapsible inline sections than footnotes?

**Comment by blujay92** [comment]
I think I'm happy with them as they are. I was thinking more that collapsible sections could be useful for hiding some uninteresting algebra, but not necessary for this post.
