### ISSUE TITLE
Rederivation of uniform recurrence relation using total expectation

### ISSUE THREAD

**Issue by mjc239** [mjc239/mjc239.github.io#9]
Merge section moved from post 1 into this section in post 2

**Comment by mjc239** [comment]
The section from post 1 was basically a summary of this section, move it back to post 2 and choose the best bits from each + integrate.

**Comment by blujay92** [comment]
Unless S is defined in a different way than i realised, E(S : P_i > s_i) is definitely not the same thing as E(S : \tau > i) so I think something needs changing in a few places.

**Comment by blujay92** [comment]
I've just pulled Turnips into my branch to read these changes and there's still places where there's this "implicit conditioning". Have you left this in on purpose or just missed some?

**Comment by blujay92** [comment]
I think that you might have perhaps added an explanatory comment, but I think it still doesn't make sense because you only want the expectations to be conditioned, not the probabilities. My personal opinion is that if you have to go so far as to single out which terms are "implicitly conditioned" then you might as well just do it explicitly. In a similar vein, as it's now mentioned twice in the space of three displayed equations I think it would be much clearer if if was just in the formulae.

**Comment by blujay92** [comment]
Otherwise I'm happy with this section!

**Comment by mjc239** [comment]
Aren't the probabilities on the RHS also conditioned on tau>=i, when using total expectation? It's just that P_i > s_i  is independent of tau>=i, so we can drop it?

**Comment by blujay92** [comment]
Yeah sorry, just the expectations that I think read confusing. Ultimately, a large part of my reason for defining tau is so as to be able to express this stuff simply so I find it odd to omit them from the four or so expectations when you have then ended up referring to it in the text two or three times.

Obviously if you disagree then happy for you to leave it as is, just struck me as odd when I read it back.

**Comment by mjc239** [comment]
Ultimately the only reason for leaving the taus out on the RHS was readability/aesthetics, but if there's any risk of confusion I think that outweighs any aesthetic arguments. I can do some modifications on it later

**Comment by blujay92** [comment]
Yeah I get you. I think when I wrote this up the first time I did something similar, but like you I found myself having to be careful to draw attention to it and it just made all the surrounding explanation bulkier.

**Comment by mjc239** [comment]
I have changed the post somewhat to address this, I think I have changed the equations enough that it would probably be best if you had a quick look over it.

**Comment by blujay92** [comment]
Made some tweaks to preserve the clarity but reduce bulk.
